#!/usr/bin/env bash
# Example Slurm batch script generated by nexa_infra.slurm.prepare_slurm_batch

#SBATCH --job-name=nexa-train
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --gpus-per-node=4
#SBATCH --time=12:00:00
#SBATCH --output=/abs/path/to/logs/slurm/%x-%A_%a.out
#SBATCH --array=0-3%2

set -euo pipefail

# Optional module/environment bootstrapping
# module load cuda/12.4
# module load python/3.11
# source /workspace/nexa_compute/.venv/bin/activate

export JOB_SPEC="/abs/path/to/spec.json"
export PYTHONUNBUFFERED=1

python3 - <<'PY'
import json
import os
import shlex
import subprocess
from pathlib import Path

specs = json.loads(Path(os.environ["JOB_SPEC"]).read_text())
task_id = int(os.environ.get("SLURM_ARRAY_TASK_ID", "0"))
if task_id < 0 or task_id >= len(specs):
    raise SystemExit(f"Invalid SLURM_ARRAY_TASK_ID {task_id}")

spec = specs[task_id]
env = dict(os.environ)
env.update(spec.get("env", {}))
command = spec["command"]

print("[slurm] launching:", " ".join(shlex.quote(token) for token in command))
subprocess.run(command, check=True, env=env)
PY
